# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KaZG/WxkriZGH6cFr0tISBJlBnrR9q0zx00+E5DVzqD8Y7vULLoxs30BvHi+P5jRq7X96W9at2avii/7EK+g4wMSb0nz2unmXO6+qdTFudLogNR7ghaW6MwrODnErrR9fOzE8Q5F+2kNzjv/7+xxLZ1vqimRyKTZJxIbbDtTnm9gnoOu/CNTIZYTuTVbtQQnnn6bhb2my+AF1rVqVyW8fUkmuQCYFVEp3LgGaFPAKDyJuKACOP5d7De9DEPvPiBlEJKZfvRtODBdL/pK/ZXVQ2kjJcovNVkWKNb5bdUzUsAd6cy9gublM42cHeCGDY/3e0bE9v692Z9mbV3Kgn9Bq2FR9PVLxcchiJdD4nZ6swoRvNsoanlAw14bJYmyoQZOQcysmk9/FAZ2u3+p1UwJmPx+2DBrePW2uHXIC3YTK2ZMlMCgWmExXmz4z4q5TMPCRwDSZaAWOmFE+gR2468DN7OHcu2s79j1Pbs6OdMlltHdecSg980iJvhWB69DbF04H5FTwJcUhl8jPqarU/JTnC//I/5B0cYCKmdYFTD0GzAk8kA9hpKEgkZK6cUn+LT29h+v6ACLlw77YSdvCFQpTDvtypsdhyzRk8eV1xc9q0D6eJn8Yd85ETR4f018NNgMY2mkGbvdHmRYBny49bvylxA5/m2VOIUHex7XtajBYgY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml