travis:
  secure:
    BINSTAR_TOKEN: KaZG/WxkriZGH6cFr0tISBJlBnrR9q0zx00+E5DVzqD8Y7vULLoxs30BvHi+P5jRq7X96W9at2avii/7EK+g4wMSb0nz2unmXO6+qdTFudLogNR7ghaW6MwrODnErrR9fOzE8Q5F+2kNzjv/7+xxLZ1vqimRyKTZJxIbbDtTnm9gnoOu/CNTIZYTuTVbtQQnnn6bhb2my+AF1rVqVyW8fUkmuQCYFVEp3LgGaFPAKDyJuKACOP5d7De9DEPvPiBlEJKZfvRtODBdL/pK/ZXVQ2kjJcovNVkWKNb5bdUzUsAd6cy9gublM42cHeCGDY/3e0bE9v692Z9mbV3Kgn9Bq2FR9PVLxcchiJdD4nZ6swoRvNsoanlAw14bJYmyoQZOQcysmk9/FAZ2u3+p1UwJmPx+2DBrePW2uHXIC3YTK2ZMlMCgWmExXmz4z4q5TMPCRwDSZaAWOmFE+gR2468DN7OHcu2s79j1Pbs6OdMlltHdecSg980iJvhWB69DbF04H5FTwJcUhl8jPqarU/JTnC//I/5B0cYCKmdYFTD0GzAk8kA9hpKEgkZK6cUn+LT29h+v6ACLlw77YSdvCFQpTDvtypsdhyzRk8eV1xc9q0D6eJn8Yd85ETR4f018NNgMY2mkGbvdHmRYBny49bvylxA5/m2VOIUHex7XtajBYgY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
